services:
  database:
    image: mysql:latest
    environment:
        - MYSQL_DATABASE=prova
        - MYSQL_USER=user
        - MYSQL_PASSWORD=user@password
        - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./MySql:/docker-entrypoint-initdb.d
  server:
    depends_on:
      - database
    build:
      context: prodotti
      target: builder
    ports:
      - 8080:8080
    volumes:
      - ./prodotti:/project
      - /project/node_modulesß
  web:
    depends_on:
      - server
    build:
      context: CMS
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./CMS:/project
      - /project/node_modulesß