services:
  database:
    container_name: database_mysql
    image: mysql:latest
    environment:
        - MYSQL_DATABASE=prova
        - MYSQL_USER=user
        - MYSQL_PASSWORD=user@password
        - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./MySql:/docker-entrypoint-initdb.d
  server:
    container_name: backend_prodotti
    depends_on:
      - database
    build:
      context: backend
      target: builder
    ports:
      - 8080:8080
    volumes:
      - ./backend:/project
      - /project/node_modules
  web:
    container_name: frontend_CMS
    depends_on:
      - server
    build:
      context: frontend
      target: builder
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/project
      - /project/node_modules